baseurl = "/"
publishDir = "docs"
title = "Alex Mwangi"
author = "Nan Xiao"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = "https-mwangialex-netlify-com"
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Data %>% Understanding %>% Insight"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/Rastechie"
    weight = 2
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/mwangialex"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/alexmwangi_ke"
    weight = 4

